platform :ios, '8.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'ChatDemo-UI3.0' do

	pod 'Hyphenate', :path => '../HyphenateFullSDK'

	pod 'EaseUI', :path => '../EaseUI'

	pod 'RedpacketAliAuthLib'
	
	#pod 'Hyphenate_VideoRecoder', :path => '../HyphenateVideoRecoder'

end

target 'ChatDemo-UI3.0-JDPay' do
    
	pod 'Hyphenate', :path => '../HyphenateFullSDK'

	pod 'EaseUI', :path => '../EaseUI'
    
    	pod 'RedpacketLib'

end
